### CREATE ONE : Créer une ressource basée sur les données de la requête
POST http://localhost:3000/films
Content-Type: application/json

{
    "id": 4,
    "title": "Le Voyage de Chihiro",
    "duration": 124,
    "budget": 19000000,
    "link": "https://www.imdb.com/title/tt0245429/"
}

### READ ONE : Lire la ressource identifiée
@urlFilm = http://localhost:3000
GET {{urlFilm}}/films/3

### READ ALL FILTERED : Lire toutes les ressources de la collection selon le filtre donné
GET {{urlFilm}}/films/?minimum-duration=100

### DELETE ONE : Effacer la ressource identifiée par l'identifiant 2
DELETE {{urlFilm}}/films/3

### UPDATE ONE : Mettre à jour les propriétés de la ressource par les valeurs données dans la requête, pour une ou plusieurs propriétés
PATCH {{urlFilm}}/films/3
Content-Type: application/json

{
    "title":"Le Château Ambulant"
}

### UPDATE ONE or CREATE ONE : Remplacer la ressource par une ressource reprenant les valeurs données dans la requête, seulement si toutes les propriétés de la ressource sont données !
PUT {{urlFilm}}/films/7
Content-Type: application/json

{
    "id": 5,
    "title": "Le Voyage de Chihiro",
    "duration": 124,
    "budget": 19000000,
    "link": "https://www.imdb.com/title/tt0245429/"
}